# Form implementation generated from reading ui file 'E:\OneDrive\Bureau\New folder\example.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(808, 656)
        MainWindow.setStyleSheet("background-color: #2a2a72;\n"
"background-image: linear-gradient(315deg, #2a2a72 0%, #009ffd 74%);\n"
"color: #fff;\n"
"font-family: \"Times New Roman\";\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 70, 391, 91))
        self.label.setStyleSheet("font-size: 42px;\n"
"font-weight: bold;\n"
"padding-left: 70px;\n"
"border: 4px solid gray;\n"
"\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 240, 431, 71))
        self.textEdit.setStyleSheet("background-color: whitesmoke;\n"
"border: 2px solid gray;")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 240, 171, 71))
        self.label_2.setStyleSheet("font-size: 32px;\n"
"font-weight: bold;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 360, 181, 71))
        self.label_3.setStyleSheet("font-size: 32px;\n"
"font-weight: bold;\n"
"")
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(310, 360, 431, 71))
        self.textEdit_2.setStyleSheet("background-color: whitesmoke;\n"
"border: 2px solid gray;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 480, 181, 71))
        self.label_4.setStyleSheet("font-size: 32px;\n"
"font-weight: bold;\n"
"")
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(310, 480, 431, 71))
        self.textEdit_3.setStyleSheet("background-color: whitesmoke;\n"
"border: 2px solid gray;")
        self.textEdit_3.setObjectName("textEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FScraper 🔍 "))
        self.label_2.setText(_translate("MainWindow", "URL:"))
        self.label_3.setText(_translate("MainWindow", "ELEMENT:"))
        self.label_4.setText(_translate("MainWindow", "Class:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
